In [1]:
import json
import pandas as pd
import numpy as np

from src.settings import EMBEDDINGS_DIR

In [2]:
pl_bert_emb_fpath = EMBEDDINGS_DIR / "polish_annotations__dkleczek__bert_base_polish_cased_v1.json"
landmarks_emb_fpath = EMBEDDINGS_DIR / "landmarks_lstm_embeddings.jsonl"

In [3]:
with open(pl_bert_emb_fpath, encoding='utf-8') as pl_bert_emb_file:
    pl_bert_embeddings = json.load(pl_bert_emb_file)

In [4]:
pl_bert_embeddings = np.array(pl_bert_embeddings)

pl_bert_embeddings.shape, pl_bert_embeddings

((40355, 768),
 array([[ 0.21002649,  0.21999882,  1.01707697, ...,  0.37352839,
         -0.20226263, -0.49486965],
        [ 0.86122519,  0.01214768,  0.75904387, ...,  0.5469867 ,
          0.0873817 ,  0.75063694],
        [ 0.44947666,  0.25013149,  1.17241311, ...,  0.42151242,
          0.48686132,  0.7445026 ],
        ...,
        [ 0.21101624, -0.10978444,  0.27456236, ...,  0.76810187,
         -0.00862992,  0.63413709],
        [ 0.7851755 ,  0.25445372,  0.74189717, ...,  0.87500304,
          0.20130366,  1.94580472],
        [-0.22382234,  0.02666697,  0.11899389, ...,  0.36734721,
          0.87697387,  0.03037993]]))

In [5]:
landmarks_emb_df = pd.read_json(landmarks_emb_fpath, lines=True, nrows=3_000)
landmarks_emb_df

,CSVName,Embedding
0,K01AF__07_122200-123160.csv,"[-1.062800765794236e-05, -2.261193003505468e-0..."
1,K01AF__07_124680-126520.csv,"[-1.096217783924657e-05, -2.2079562768340114e-..."
2,K01AF__07_130400-132120.csv,"[-9.714613042888232e-06, -2.1375686628744003e-..."
3,K01AF__07_132120-132600.csv,"[-1.0957579434034411e-05, -2.1563027985394004e..."
4,K01AF__07_132600-133840.csv,"[-1.129780321207363e-05, -2.295026206411421e-0..."
...,...,...
2995,K11BF01-14__07_640880-642400.csv,"[-9.839119229582138e-06, -2.2101652575656775e-..."
2996,K11BF01-14__07_643440-644640.csv,"[-9.195749953505583e-06, -2.091986243613064e-0..."
2997,K11BF01-14__07_65040-66480.csv,"[-1.05123490357073e-05, -2.309537376277148e-05..."
2998,K11BF01-14__07_650440-651840.csv,"[-1.009884181257803e-05, -2.0229141227900982e-..."
2999,K11BF01-14__07_654080-655480.csv,"[-9.917990610119887e-06, -2.1574611309915784e-..."

In [7]:
np.array(landmarks_emb_df.Embedding[3]).shape

(38400,)

In [8]:
landmarks_emb_df["EmbeddingLen"] = landmarks_emb_df.Embedding.apply(len)
landmarks_emb_df

,CSVName,Embedding,EmbeddingLen
0,K01AF__07_122200-123160.csv,"[-1.062800765794236e-05, -2.261193003505468e-0...",71168
1,K01AF__07_124680-126520.csv,"[-1.096217783924657e-05, -2.2079562768340114e-...",22016
2,K01AF__07_130400-132120.csv,"[-9.714613042888232e-06, -2.1375686628744003e-...",29184
3,K01AF__07_132120-132600.csv,"[-1.0957579434034411e-05, -2.1563027985394004e...",38400
4,K01AF__07_132600-133840.csv,"[-1.129780321207363e-05, -2.295026206411421e-0...",9728
...,...,...,...
2995,K11BF01-14__07_640880-642400.csv,"[-9.839119229582138e-06, -2.2101652575656775e-...",137216
2996,K11BF01-14__07_643440-644640.csv,"[-9.195749953505583e-06, -2.091986243613064e-0...",7168
2997,K11BF01-14__07_65040-66480.csv,"[-1.05123490357073e-05, -2.309537376277148e-05...",34816
2998,K11BF01-14__07_650440-651840.csv,"[-1.009884181257803e-05, -2.0229141227900982e-...",66048
2999,K11BF01-14__07_654080-655480.csv,"[-9.917990610119887e-06, -2.1574611309915784e-...",16384

In [9]:
landmarks_emb_df.describe()

        EmbeddingLen
count    3000.000000
mean    30191.445333
std     25746.535816
min      2048.000000
25%     12800.000000
50%     22528.000000
75%     38912.000000
max    217088.000000